name: MLflow CI Training

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: file:${{ github.workspace }}/mlruns

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install mlflow pandas scikit-learn joblib jq

      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local

      - name: Get latest MLflow run ID
        run: |
          RUN_ID=$(mlflow runs list --max-results 1 --output json | jq -r '.[0].run_id')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest RUN_ID: $RUN_ID"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Transition model to Production
        run: |
          mlflow models transition-stage \
            --model-name DiabetesRandomForest \
            --version 1 \
            --stage Production

      - name: Build Docker Image with MLflow
        run: |
          mlflow models build-docker \
            -m models:/DiabetesRandomForest/Production \
            -n ${{ secrets.DOCKER_USERNAME }}/diabetes-rf:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/diabetes-rf:latest
